// 4-vue/src/Banner.vue
<template>
  <div class="banner">
    <img :src="tile" :alt="title" class="tile" />

    <div class="overlay">
      <img :src="logo" :alt="logoAlt" class="network" />

      <h3 class="title">
        {{ title }}
      </h3>
    </div>
  </div>
</template>

<script>
  export default {
    props: {
      tile: String,
      title: String,
      logo: {
        type: String,
        default: '../logo.png',
      },
      logoAlt: {
        type: String,
        default: '7plus',
      },
    },
  };
</script>

<style scoped>
  .banner {
    position: relative;
    display: inline-block;
  }

  .tile {
    display: block;
  }

  .overlay {
    position: absolute;
    bottom: 0;
    box-sizing: border-box;
    display: flex;
    align-items: center;
    width: 100%;
    padding: 1rem;
    background-color: rgba(0, 0, 0, 0.5);
  }

  .network {
    width: auto;
    height: 4.6rem;
  }

  .title {
    margin: 0 0 0 1rem;
    font-family: sans-serif;
    font-size: 2.2rem;
    color: rgb(255, 255, 255);
  }
</style>

// 3-preact/src/Banner.jsx
import { h } from 'preact';
import styled from 'styled-components';
import PropTypes from 'prop-types';

const Wrapper = styled.div`
  position: relative;
  display: inline-block;
`;

const TileImage = styled.img`
  display: block;
`;

const Overlay = styled.div`
  position: absolute;
  display: flex;
  align-items: center;
  width: 100%;
  padding: 1rem;
  box-sizing: border-box;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
`;

const NetworkLogo = styled.img`
  width: auto;
  height: 4.6rem;
`;

const Title = styled.h3`
  margin: 0 0 0 1rem;
  color: rgb(255, 255, 255);
  font-family: sans-serif;
  font-size: 2.2rem;
`;

const Banner = ({
  className,
  tile,
  title,
  logo,
  logoAlt,
}) => (
  <Wrapper className={className}>
    <TileImage src={tile} alt={title} />

    <Overlay>
      <NetworkLogo src={logo} alt={logoAlt} />

      <Title>
        {title}
      </Title>
    </Overlay>
  </Wrapper>
);

Banner.propTypes = {
  tile: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  className: PropTypes.string,
  logo: PropTypes.string,
  logoAlt: PropTypes.string,
};

Banner.defaultProps = {
  className: '',
  logo: '../logo.png',
  logoAlt: '7plus',
};

export default Banner;
